export const VARIANTS = [
  {
    id: 'v01-thread-recap',
    title: 'Thread Recap + Action Items',
    workspace: 'acme-eng',
    channel: 'build',
    topic: 'Builds, releases, and CI',
    sidebarChannels: ['build', 'eng', 'incidents', 'support', 'releases', 'random'],
    sidebarDms: ['alex', 'maria', 'sam', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Yash',
        avatar: 'YA',
        time: '9:41 AM',
        text: '@μEmployee can you recap the last 7 days in #build and extract action items?',
      },
      { kind: 'typing', who: 'μEmployee', duration: 900 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '9:41 AM',
        text: 'Queued as #42. Pulling threads + replies now.',
        blocks: [
          { type: 'list', title: 'Tool calls', items: ['slack.history (#build, 7d)', 'slack.thread (for each top thread)', 'web.search (links mentioned)', 'context.write (summary)'] },
        ],
      },
      { kind: 'typing', who: 'μEmployee', duration: 700 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '9:43 AM',
        text: 'Done. Posted a recap and uploaded a markdown report.',
        blocks: [
          {
            type: 'list',
            title: 'Highlights',
            items: [
              'CI flake cluster: 3 tests (owners tagged)',
              'Release v1.12 blockers: 2 (ETA aligned)',
              'Infra migration decision: approved (doc linked)',
            ],
          },
          { type: 'list', title: 'Action items', items: ['Fix flaky tests + add retries', 'Pin release checklist to channel', 'Update runbook with new deploy steps'] },
        ],
        files: [{ ext: 'md', name: 'build-weekly-recap.md', sub: 'recap + action items' }],
      },
    ],
  },
  {
    id: 'v02-incident-commander',
    title: 'Incident Protocol + Scheduled Updates',
    workspace: 'acme-eng',
    channel: 'incidents',
    topic: 'Production incidents and status updates',
    sidebarChannels: ['incidents', 'eng', 'build', 'support', 'releases', 'random'],
    sidebarDms: ['oncall', 'maria', 'alex', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Maria',
        avatar: 'MA',
        time: '10:03 AM',
        text: '@μEmployee we have elevated 5xx. Start incident protocol and post updates every 15m.',
      },
      { kind: 'typing', who: 'μEmployee', duration: 800 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '10:03 AM',
        text: 'Acknowledged. Creating a war room and pinning an initial status update.',
        blocks: [
          { type: 'list', title: 'Checklist', items: ['Create #inc-427 channel', 'Assign roles (IC, Comms, Ops)', 'Post impact + scope', 'Start 15m updates'] },
        ],
      },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '10:04 AM',
        text: 'Proposed: enable a cron job for updates (every 15 minutes) in this channel.',
        blocks: [
          { type: 'buttons', buttons: [{ id: 'approve_updates', label: 'Approve', variant: 'primary' }, { id: 'deny_updates', label: 'Deny', variant: 'danger' }] },
        ],
      },
      { kind: 'click', buttonId: 'approve_updates', resultText: 'Approved' },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '10:04 AM',
        text: 'Cron enabled. First update in 2 minutes.',
        blocks: [{ type: 'section', text: 'Current status: Investigating. Suspect: upstream auth timeouts.' }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 600 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '10:06 AM',
        text: 'Update 1/?: Impact reduced after traffic shift. Next update at 10:21 AM.',
        blocks: [
          { type: 'list', title: 'Signals', items: ['5xx down 62%', 'p95 latency down 38%', 'error budget stabilized'] },
        ],
      },
    ],
  },
  {
    id: 'v03-pr-review',
    title: 'PR Review + Risk Callouts',
    workspace: 'acme-eng',
    channel: 'eng',
    topic: 'Engineering discussion',
    sidebarChannels: ['eng', 'build', 'releases', 'incidents', 'support', 'random'],
    sidebarDms: ['alex', 'sam', 'maria', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Alex',
        avatar: 'AL',
        time: '2:18 PM',
        text: 'Can you review https://github.com/acme/microemployee/pull/812 and summarize risk areas?',
      },
      { kind: 'typing', who: 'μEmployee', duration: 1000 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '2:18 PM',
        text: 'On it. Fetching diff + related files and scanning for regressions.',
        blocks: [{ type: 'list', title: 'Tool calls', items: ['web.fetch (PR page)', 'slack.search (related incidents)', 'context.write (review notes)'] }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 700 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '2:22 PM',
        text: 'Review posted. Main risks are around auth edge cases and retry semantics.',
        blocks: [
          { type: 'list', title: 'Risk areas', items: ['Token refresh on 401 can loop', 'New retry policy changes idempotency', 'DB migration needs a backfill guard'] },
          { type: 'code', text: 'if (status === 401) {\n  // add max-attempts + circuit-breaker\n  refresh();\n  retry();\n}' },
        ],
        files: [{ ext: 'md', name: 'pr-812-review.md', sub: 'findings + suggested fixes' }],
      },
    ],
  },
  {
    id: 'v04-standup-digest',
    title: 'Standup Digest + Blockers',
    workspace: 'acme-eng',
    channel: 'standup',
    topic: 'Daily updates',
    sidebarChannels: ['standup', 'eng', 'build', 'incidents', 'releases', 'random'],
    sidebarDms: ['sam', 'alex', 'maria', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Sam',
        avatar: 'SA',
        time: '9:05 AM',
        text: "@μEmployee summarize yesterday's standup thread and call out blockers.",
      },
      { kind: 'typing', who: 'μEmployee', duration: 850 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '9:05 AM',
        text: 'Queued as #103. Reading the standup thread (replies + mentions).',
        blocks: [{ type: 'list', title: 'Tool calls', items: ['slack.thread (standup)', 'slack.get_user (owners)', 'context.write (digest)'] }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 650 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '9:07 AM',
        text: 'Standup digest posted.',
        blocks: [
          { type: 'list', title: 'Done', items: ['Merged feature flag cleanup', 'Shipped v1.11.3 hotfix'] },
          { type: 'list', title: 'Doing', items: ['CI perf improvements', 'Admin SPA route fixes'] },
          { type: 'list', title: 'Blocked', items: ['Need DB index approval for billing query', 'Waiting on vendor rate limit increase'] },
        ],
        files: [{ ext: 'md', name: 'standup-digest.md', sub: 'yesterday summary' }],
      },
    ],
  },
  {
    id: 'v05-support-triage',
    title: 'Support Triage + Ticket Draft',
    workspace: 'acme-eng',
    channel: 'support',
    topic: 'Customer issues and triage',
    sidebarChannels: ['support', 'eng', 'incidents', 'build', 'releases', 'random'],
    sidebarDms: ['support-oncall', 'alex', 'maria', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Support',
        avatar: 'SU',
        time: '1:12 PM',
        text: '@μEmployee customer reports HTTP 500 on /checkout. Can you triage and draft a ticket?',
        files: [{ ext: 'txt', name: 'logs.txt', sub: 'error excerpt' }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 900 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '1:12 PM',
        text: 'Downloading the attachment and correlating with recent deploys.',
        blocks: [{ type: 'list', title: 'Tool calls', items: ['slack.files.download', 'slack.search (error signature)', 'context.write (ticket draft)'] }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 650 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '1:15 PM',
        text: "Triage summary: looks like a null cart edge case introduced in today's deploy.",
        blocks: [
          { type: 'list', title: 'Next actions', items: ['Roll back checkout service', 'Add guard for empty cart', 'Add regression test'] },
        ],
        files: [{ ext: 'md', name: 'ticket-draft.md', sub: 'ready to paste into tracker' }],
      },
    ],
  },
  {
    id: 'v06-release-notes',
    title: 'Release Notes Generator',
    workspace: 'acme-eng',
    channel: 'releases',
    topic: 'Release coordination',
    sidebarChannels: ['releases', 'build', 'eng', 'support', 'incidents', 'random'],
    sidebarDms: ['release-bot', 'alex', 'sam', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Yash',
        avatar: 'YA',
        time: '4:30 PM',
        text: "@μEmployee generate release notes for v1.12 from this week's merged PRs.",
      },
      { kind: 'typing', who: 'μEmployee', duration: 950 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '4:30 PM',
        text: 'Collecting merged PRs and categorizing changes (features, fixes, infra).',
        blocks: [{ type: 'list', title: 'Tool calls', items: ['web.search (merged PRs)', 'web.fetch (PR bodies)', 'context.write (release notes)'] }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 650 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '4:33 PM',
        text: 'Release notes ready.',
        blocks: [
          { type: 'list', title: 'Sections', items: ['Features (5)', 'Fixes (9)', 'Infra (3)', 'Known issues (1)'] },
        ],
        files: [{ ext: 'md', name: 'release-notes-v1.12.md', sub: 'copy/paste ready' }],
      },
    ],
  },
  {
    id: 'v07-context-runbook',
    title: 'Turn A Thread Into A Runbook',
    workspace: 'acme-eng',
    channel: 'ops',
    topic: 'Runbooks and operations',
    sidebarChannels: ['ops', 'incidents', 'eng', 'build', 'releases', 'random'],
    sidebarDms: ['ops-oncall', 'maria', 'sam', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Maria',
        avatar: 'MA',
        time: '11:10 AM',
        text: '@μEmployee turn this thread into a runbook in /data/context and add it to INDEX.md.',
      },
      { kind: 'typing', who: 'μEmployee', duration: 900 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '11:10 AM',
        text: 'Extracting steps, owners, and links. Writing a durable doc.',
        blocks: [{ type: 'list', title: 'Context writes', items: ['/data/context/runbook-db-latency.md', '/data/context/INDEX.md (one-line entry)'] }],
      },
      { kind: 'typing', who: 'μEmployee', duration: 650 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '11:13 AM',
        text: 'Runbook created and indexed.',
        blocks: [{ type: 'section', text: 'Path: /data/context/runbook-db-latency.md' }],
        files: [{ ext: 'md', name: 'runbook-db-latency.md', sub: 'durable ops doc' }],
      },
    ],
  },
  {
    id: 'v08-guardrail-approval',
    title: 'Command Guardrail + Approval Buttons',
    workspace: 'acme-eng',
    channel: 'deploys',
    topic: 'Deploys and operational actions',
    sidebarChannels: ['deploys', 'incidents', 'eng', 'build', 'releases', 'random'],
    sidebarDms: ['oncall', 'alex', 'maria', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Alex',
        avatar: 'AL',
        time: '3:02 PM',
        text: '@μEmployee can you run a one-time backfill for account 314 and post the output?',
      },
      { kind: 'typing', who: 'μEmployee', duration: 850 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '3:02 PM',
        text: 'This requires approval (command execution). Proposed command:',
        blocks: [
          { type: 'code', text: './scripts/backfill --account 314 --dry-run=false' },
          { type: 'buttons', buttons: [{ id: 'approve_cmd', label: 'Approve', variant: 'primary' }, { id: 'deny_cmd', label: 'Deny', variant: 'danger' }] },
        ],
      },
      { kind: 'click', buttonId: 'approve_cmd', resultText: 'Approved' },
      { kind: 'typing', who: 'μEmployee', duration: 700 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '3:04 PM',
        text: 'Backfill complete. Uploading output.',
        files: [{ ext: 'txt', name: 'backfill-output.txt', sub: 'command stdout (redacted)' }],
      },
    ],
  },
  {
    id: 'v09-morning-digest',
    title: 'Daily Digest Cron Proposal',
    workspace: 'acme-eng',
    channel: 'eng',
    topic: 'Engineering discussion',
    sidebarChannels: ['eng', 'incidents', 'deploys', 'build', 'support', 'random'],
    sidebarDms: ['alex', 'sam', 'maria', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'Yash',
        avatar: 'YA',
        time: '8:55 AM',
        text: '@μEmployee every morning, post a short digest: open incidents, queue depth, and last deploy status.',
      },
      { kind: 'typing', who: 'μEmployee', duration: 900 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '8:55 AM',
        text: 'Proposed schedule: weekdays at 9:00 AM. Approve to enable?',
        blocks: [
          { type: 'list', title: 'Digest fields', items: ['Open incidents', 'Task queue depth', 'Most recent deploy summary'] },
          { type: 'buttons', buttons: [{ id: 'approve_digest', label: 'Approve', variant: 'primary' }, { id: 'deny_digest', label: 'Deny', variant: 'danger' }] },
        ],
      },
      { kind: 'click', buttonId: 'approve_digest', resultText: 'Approved' },
      { kind: 'typing', who: 'μEmployee', duration: 600 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '9:00 AM',
        text: 'Sample digest:',
        blocks: [
          { type: 'list', title: 'Today', items: ['Incidents: 0 open', 'Queue: 3 queued, 1 running', 'Deploy: green (v1.12.0)'] },
        ],
      },
    ],
  },
  {
    id: 'v10-onboarding-helper',
    title: 'Onboarding Quickstart Answer',
    workspace: 'acme-eng',
    channel: 'onboarding',
    topic: 'New hires and onboarding',
    sidebarChannels: ['onboarding', 'eng', 'build', 'support', 'random', 'releases'],
    sidebarDms: ['new-hire', 'sam', 'alex', 'μEmployee'],
    steps: [
      {
        kind: 'msg',
        from: 'user',
        name: 'New hire',
        avatar: 'NH',
        time: '11:48 AM',
        text: '@μEmployee where is the architecture doc and how do I run it locally?',
      },
      { kind: 'typing', who: 'μEmployee', duration: 950 },
      {
        kind: 'msg',
        from: 'bot',
        name: 'μEmployee',
        avatar: 'μ',
        time: '11:48 AM',
        text: 'Here is a quickstart and pointers to the docs.',
        blocks: [
          { type: 'list', title: 'Quickstart', items: ['cd grail && cargo run -p grail-server', 'Set ADMIN_PASSWORD + Slack tokens', 'Open /admin to configure'] },
          { type: 'list', title: 'Docs', items: ['AGENTS.md (repo overview)', 'Admin: /admin/status + /admin/settings', 'Context: /data/context/*'] },
        ],
        files: [{ ext: 'md', name: 'onboarding-quickstart.md', sub: 'copy/paste steps' }],
      },
    ],
  },
];
